# Generated by Django 5.0.4 on 2024-04-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='attendance',
            field=models.CharField(max_length=50),
        ),
    ]
