# Generated by Django 5.0.4 on 2024-04-27 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_classes_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_name',
        ),
    ]
